version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: justblog-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: yourpassword
      MYSQL_DATABASE: justblog
      MYSQL_USER: justblog_user
      MYSQL_PASSWORD: justblog_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/mysql-setup.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data:
